language: cpp

#osx_image: xcode7.2

os:
 - osx

compiler:
 - clang
# - gcc

before_install:
 - brew update
 - brew install cmake || brew outdated cmake || brew upgrade cmake
 - brew install ffmpeg
 - brew install python3
 - brew install sdl2
 - brew install libsndfile
 - brew install jack
 - brew install fftw
 - sudo pip3 install numpy
# - sudo apt-get update -qq
# - sudo apt-get install -qq python3-all-dev python3-numpy libopenal-dev libsdl2-dev libsndfile1-dev libavcodec-ffmpeg-dev libavformat-ffmpeg-dev libavutil-ffmpeg-dev libjack-dev

before_script:
 - mkdir build
 - cd build
 - ls /usr/local/lib/python3.5
 - cmake -DPYTHON_INCLUDE_DIR=/usr/local/lib/python3.5/include -DPYTHON_LIBRARY=/usr/local/lib/python3.5/libpython3.5.dylib ..

script:
 - make

